sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master
    - fix-travis

services: docker

env:
  global:
  - KITCHEN_YAML=.kitchen.yml
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
  matrix:
  - INSTANCE=default-amazonlinux
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-debian-8
  - INSTANCE=default-debian-9
  - INSTANCE=default-fedora-26
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  allowed_failures:

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
